root_path = '/proot/'
raid_path = '/praid/'
# root_path = 'E://datasets'
data_path = f'{raid_path}/.data'
cache_path = f'.cache'
checkpoint_path = f'.cache'

sentence_transformer = ''
vocab_name = ''
tokenizer_name = ''