FROM huggingface/transformers-pytorch-gpu
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONIOENCODING=utf-8

RUN pip install sentence-transformers datasets nltk numpy pandas tqdm torchtext pytorch-model-summary